repos:
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: v{{ cookiecutter.ruff }}
    hooks:
      - id: ruff
        # Ignore jupyter notebooks
        types_or: [ python, pyi ]
        args: [ --fix ]
  - repo: https://github.com/psf/black
    rev: {{ cookiecutter.black }}
    hooks:
      - id: black
        language_version: python3.12
        exclude: migrations
  - repo: https://github.com/pycqa/isort
    rev: v{{ cookiecutter.isort }}
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v{{ cookiecutter.pre-commit-hooks }}
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: debug-statements
      - id: detect-private-key
      - id: no-commit-to-branch
