include:
  - docker-compose.yml

services:
  app:
    environment:
      DJANGO_SETTINGS_MODULE: {{ cookiecutter.project_app }}.settings.deploy
      ENVIRONMENT: local
      DJANGO_SECRET_KEY: insecure-dev-key
      DOMAIN: localhost
      SESSION_COOKIE_SECURE: "False"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: deploy
    command: ["uwsgi", "--show-config"]
    depends_on:
      - db:db
    ports:
      - "8000:8000"